- name: Install AWS CLI on EC2 Instances
  hosts: servers
  become: yes
  tasks:
    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    - name: Ensure unzip is installed
      package:
        name: unzip
        state: present

    - name: Check if AWS CLI is installed
      command: "aws --version"
      register: aws_cli_check
      ignore_errors: true

    - name: Download AWS CLI installation script using curl
      command: curl -o /tmp/awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      when: aws_cli_check.failed

    - name: Unzip AWS CLI installation package
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"
        remote_src: yes
      when: aws_cli_check.failed

    - name: Run AWS CLI installer
      command: "/tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin --update"
      when: aws_cli_check.failed

    - name: Verify AWS CLI installation
      command: "aws --version"
      register: aws_cli_version

    - debug:
        msg: "AWS CLI version: {{ aws_cli_version.stdout }}"
